---
- name: Download zplugin installer
  get_url:
    url: https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh
    dest: $HOME/zplugin-installer.sh
    mode: 0755

- name: Execute the zplugin installer
  shell: $HOME/zplugin-installer.sh

- name: Remove the zplugin installer
  file:
    path: $HOME/zsh-installer.sh
    state: absent